# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170405_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30, verbose_name='年龄'),
        ),
    ]
