# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='study_num',
            new_name='students',
        ),
    ]
