# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170404_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=52, verbose_name='课程名字'),
        ),
    ]
