# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='www.baidu.com', verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
