# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '邮箱'), ('forget', '修改密码'), ('update_email', '修改邮箱')], max_length=18, verbose_name='验证码类型'),
        ),
    ]
